name: ciofs-freshwater-report
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Required for full project functionality (dont remove)
  - pytest=8.3.2
  - cf_pandas=0.8.1
  - cf_xarray=0.10.0
  - cmocean=4.0.3
  - extract_model
  - fastparquet=2024.2.0
  - geoviews=1.12.0
  - hvplot=0.10.0
  - intake==2.0.7
  - jupyter
  - jupyter-book
  - jupytext=1.16.4
  - matplotlib-base=3.9.1
  - ocean-model-skill-assessor=1.3.2
  - pandas=2.2.2
  - pip=24.2
  - seaborn=0.13.2
  - xcmocean=0.3.2
  - docutils==0.17.1
  - pip:
    - intake-coops==0.4.0
    #- docutils==0.17.1  # jupyter-book recommends this as of 10/9/24: https://jupyterbook.org/en/stable/content/citations.html
    # - cook-inlet-catalogs
    # - report-tools
  #   - geopy
  #   - git+https://github.com/intake/intake.git
  #   - git+https://github.com/axiom-data-science/cook-inlet-catalogs.git
