version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ciofs_freshwater
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - /mnt/vault/ciofs:/mnt/vault/ciofs:ro
      - /mnt/vault/ciofs/input:/mnt/vault/ciofs/input
    command: /bin/bash -c "source /opt/conda/bin/activate && cd /app && ./run.sh"