# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CIOFS Freshwater Comparison Report
author: Kristen M. Thyng, Chang Liu, Axiom Data Science
copyright: "2024"
logo:  Tt_Axiom_logo_hori_blk.jpg
# Auto-exclude files not in the toc
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 1800
  exclude_patterns          : ["ciofs-skill-assessment/ciofs_skill_assessment/report/overview_moorings.ipynb",
                               "ciofs-skill-assessment/ciofs_skill_assessment/report/overview_adcp.md",
                               ciofs-skill-assessment/ciofs_skill_assessment/report/overview_ctd_transects.ipynb
                               ]    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  # exclude_patterns          : ["*.ipynb"]    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  allow_errors              : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year


# # Information about where the book exists on the web
# repository:
#   # url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#   path_to_book: docs  # Optional path to your book, relative to the repository root
#   branch: master  # Which branch of the repository should be used when creating links (optional)

# # Add GitHub buttons to your book
# # See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:
#   use_issues_button: true
#   use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

sphinx:
  config: 
   suppress_warnings: [mystnb.unknown_mime_type]  # key-value pairs to directly over-ride the Sphinx configuration