name: ciofs-freshwater-report
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Required for full project functionality (dont remove)
  - pytest
  - cartopy=0.23.0  # with 0.25.0 overview_moorings compilation stopped on 2nd overview plot
  - cf_pandas
  - cf_xarray
  - cmocean
  # - extract_model>=1.4.4
  - fastparquet
  - geoviews
  - holoviews=1.19.1  # otherwise the drifter overview plots were impossibly slow with newer version
  - hvplot
  - intake==2.0.7
  - jupyter
  - jupyter-book
  - jupytext
  - matplotlib-base
  - ocean-model-skill-assessor=1.3.2
  - pandas
  - pip
  - playwright
  - PyPDF2
  - pyppeteer
  - seaborn
  - xcmocean=0.3.2
  - docutils==0.17.1
  # also install locally: cook-inlet-catalogs, report-utils
  - pip:
    - extract_model>=1.4.4
    - intake-coops
    - cook-inlet-catalogs==1.0.1
    #- docutils==0.17.1  # jupyter-book recommends this as of 10/9/24: https://jupyterbook.org/en/stable/content/citations.html
    # - cook-inlet-catalogs
    # - report-tools
  #   - geopy
  #   - git+https://github.com/intake/intake.git
    # - git+https://github.com/axiom-data-science/cook-inlet-catalogs.git
